#!/usr/bin/env sh
# Build a single chapter into its own PDF.
#
# Chapter .tex files are fragments: they start at \chapter and have no
# \documentclass, so latexmk cannot compile them directly. This script
# generates a throwaway root document (temp_manuscript.tex, gitignored) that
# reuses the full preamble of Thesis.tex and imports just the one chapter.
# That is what the "% !TEX root = ../../../temp_manuscript.tex" magic comment
# at the top of each chapter refers to.
#
# Usage:
#   ./build-chapter.sh Chapters/Backmatter/Portfolio/Portfolio.tex
#
# Result: Portfolio.pdf in the repository root.

set -eu

CHAPTER="${1:?usage: $0 <path/to/Chapter.tex>}"

if [ ! -f "$CHAPTER" ]; then
	echo "$0: no such file: $CHAPTER" >&2
	exit 1
fi

MAIN="${MAIN:-Thesis}"
TEMP="temp_manuscript"
DIR=$(dirname "$CHAPTER")
BASE=$(basename "$CHAPTER")
OUT=$(basename "$CHAPTER" .tex)

# Everything in Thesis.tex before \begin{document} is the preamble: document
# class, thesis.sty, all Settings/ imports and the bibliography resources.
awk '/^\\begin\{document\}/{exit} {print}' "$MAIN.tex" > "$TEMP.tex"

cat >> "$TEMP.tex" <<EOF

%% ------------------------------------------------------------------
%% Generated by build-chapter.sh -- do not edit, do not commit.
%% Single-chapter preview of: $CHAPTER
%% ------------------------------------------------------------------
\\begin{document}
\\sloppy
\\pagenumbering{arabic}
\\mainmatter
\\subimport{$DIR/}{$BASE}
\\printbibliography[heading=bibintoc]
\\end{document}
EOF

latexmk -pdf -file-line-error -interaction=nonstopmode "$TEMP.tex"

mv "$TEMP.pdf" "$OUT.pdf"
# The PDF is renamed above, so every remaining temp_manuscript.* is auxiliary
rm -f "$TEMP".*

echo "$0: wrote $OUT.pdf"
